Baseline model & Fast API
crypto-sentiment/crypto_sentiment_model_fast_api pull request #1
Opened 2022-04-06 12:10 UTC by Yorko

Added:
 - model training 
 - Fast API wrapping the model

See Readme for details.

2022-04-06 18:08 UTC, labdmitriy commented on .pre-commit-config.yaml
> +    -   id: black
Будем ли использовать в pre-commit hooks тот же набор правил, что и устанавливаем из requirements (например, isort)?
Будем ли использовать flake8 и mypy?

2022-04-06 18:21 UTC, labdmitriy commented on src/api.py
> +from src.utils import get_project_root
Когда разворачивали у себя среду для проекта, нашли удобным следущие моменты:
- Оборачивать в Python package, чтобы можно было бы установить его в editable mode - для импорта из вложенных папок с модулями, или notebooks, а также для возможности изменений модуля без переустановок и реимпорта функционала
- Именовать package не src, а названием, относящимся к (или равным)  distribution name. Например, scikit-learn - distribution name, sklearn - package name.
Так оказалось удобнее использовать фунrционал в сторонних библиотеках, иначе получим название src для всех библиотек. Сами в свое время перешли с src на \<package name\>, подсмотрели во второй версии cookiecutter-ds: 
https://github.com/drivendata/cookiecutter-data-science/tree/v2

2022-04-06 18:24 UTC, labdmitriy commented on src/api.py
> +with open(str(project_root / "config.yml")) as f:
Вроде оборачивать в str() не нужно, Path работает хорошо в таких случаях (где-то еще видел такое преобразование)

2022-04-06 18:35 UTC, labdmitriy commented on src/data.py
> +    params: Dict[str, Any] = yaml.load(f, Loader=yaml.FullLoader)
Мы на одном из других курсов по MLOps использовали объект ConfigBox из библиотеки box, удобно преобразует параметры в нужные типы, и такой объект передавали из __main__ в функции с pipeline, используя argparse для передачи доп. параметров:
https://gitlab.com/labdmitriy/hat-client/-/blob/master/hat_client/pipelines/model_training.py

2022-04-06 18:36 UTC, labdmitriy commented on src/data.py
> +        / params["data"]["train_filename"]
Вроде должно без Path() отработать и автоматически сконвертируется в Path (т.к. project_root типа Path)

2022-04-06 18:38 UTC, labdmitriy commented on src/api.py
> +    """
Какой мы будет тип docstring использовать? Это формат reST?

2022-04-06 18:49 UTC, labdmitriy commented on requirements.txt
> +uvicorn >= 0.17.6
В poetry есть возможность автоматически отслеживать устанавливаемые библиотеки, неявные устанавливаемые зависимости, а также разделять на dev и prod пакеты, оказалось очень удобно при дальнешей передаче минимального необходимого набора библиотек со всеми зависимостями в production. 
Также он умеет фиксировать версию python.

2022-04-06 18:55 UTC, labdmitriy commented on src/train.py
> +
Для сравнения baseline с дальнейшими моделями, будем отделять test dataset?

2022-04-07 10:36 UTC, Yorko commented on .pre-commit-config.yaml
> +    -   id: black
Добавил все кроме `MyPy`, c ним у меня не сложилось, показалось, что больше ограничений, чем профита. Но можно меня переубедить в отдельном PR :)

2022-04-07 10:37 UTC, Yorko commented on src/api.py
> +from src.utils import get_project_root
Переименовал `src` в `cryptonews_sentiment_base_model`, отдельный package пока не делал

2022-04-07 10:38 UTC, Yorko commented on src/api.py
> +with open(str(project_root / "config.yml")) as f:
fixed in fa29b12

2022-04-07 10:39 UTC, Yorko commented on src/data.py
> +    params: Dict[str, Any] = yaml.load(f, Loader=yaml.FullLoader)
Пока не вижу необходимости, честно говоря. Конфиг очень простой. Позже обсудим, как будем действовать в случае большого числа конфигов, скорее в сторону Hydra смотреть.

2022-04-07 10:39 UTC, Yorko commented on src/data.py
> +        / params["data"]["train_filename"]
fixed in fa29b12

2022-04-07 10:40 UTC, Yorko commented on requirements.txt
> +uvicorn >= 0.17.6
Да, тоже юзаю poetry (наелся с ее багами тоже нехило), казалось оверкиллом. Но хорошо, все же передал с поетри

2022-04-07 10:43 UTC, Yorko commented on src/train.py
> +
В задачах с такими маленькими выборками я не делаю отложенную, т.к. она слишком мала будет. По классике мы оставляем отложенную, скажем, 30%, на остальных 70% гоним кросс-валидацию, тюним фичи/параметры и т.д. и только в самом конце (один раз всего в идеале!) мы сверяемся по отложенной выборке. Проблема в том, что на практике никто не сверяется на ней только один раз, а поэтому происходит переобучение под отложенную выборку. С большими сетами – без проблем, а вот когда несколько тысяч примеров можно просто CV использовать.

2022-04-07 10:46 UTC, Yorko commented on src/api.py
> +    """
Это тот что PyCharm подсовывает, точно не знаю. Обсудим - если захотим запилить автоматическую документацию с sphinx, думаю, от этого надо плясать. Меня устраивает и PyCharm-style, и Google-style.

2022-04-07 10:47 UTC, Yorko commented on src/api.py
> +from src.utils import get_project_root
@labdmitriy хочешь докинуть коммит с оборачиванием всего этого дела в пакет?

2022-04-07 11:05 UTC, Yorko commented on src/api.py
> +from src.utils import get_project_root
Хотя это ж можно с поетри как раз сделать, окей, я добью. Но это может отдельным пиаром пойти, кажется, не блокер для текущего.

2022-04-07 11:30 UTC, aleksandrinvictor requested changes

2022-04-07 11:30 UTC, aleksandrinvictor commented on cryptonews_sentiment_base_model/train.py
> +    cross_val_params = params["cross_validation"]
Этот код повторяется в нескольких файлах. Может стоит вынести его в utills и сделать функцию read_config?

2022-04-07 11:30 UTC, aleksandrinvictor commented on cryptonews_sentiment_base_model/train.py
> +            cross_val=cross_val_params["cv_perform_cross_val"],
Можно конфиг обернуть с помощью https://github.com/rbehzadan/ddict, чтобы получать значения из словаря точкой.

2022-04-07 11:30 UTC, aleksandrinvictor commented on cryptonews_sentiment_base_model/model.py
> +    params: Dict[str, Any] = yaml.load(f, Loader=yaml.FullLoader)
Этот код здесь кажется не нужен. Возможно остался после отладки.

2022-04-07 11:30 UTC, aleksandrinvictor commented on cryptonews_sentiment_base_model/inference.py
> +):
```suggestion
) -> Dict[str, str]:
```

2022-04-07 11:30 UTC, aleksandrinvictor commented on cryptonews_sentiment_base_model/model.py
> +def initialize_model(params: dict) -> Pipeline:
```suggestion
def initialize_model(params: Dict[str, Any]) -> Pipeline:
```

2022-04-07 12:06 UTC, labdmitriy commented on src/api.py
> +from src.utils import get_project_root
Это единственная пока обнаруженная проблема с poetry, которую я нашел в текущей версии - невозможность установить локальный проект в editable mode через poetry (они в какой-то момент выпилили эту фичу, и вроде в новой major версии появится снова), поэтому там требуется пока setup.py.
Но это вообще не проблема, особенно если использовать настроенный шаблон cookiecutter-ds.

2022-04-07 12:12 UTC, labdmitriy approved these changes

2022-04-07 13:07 UTC, Yorko commented on cryptonews_sentiment_base_model/train.py
> +            cross_val=cross_val_params["cv_perform_cross_val"],
Дима уже ранее ConfigBox советовал для того же самого :) давайте пока отложим это решение

2022-04-07 13:20 UTC, Arsenaut requested changes

2022-04-07 13:20 UTC, Arsenaut commented on cryptonews_sentiment_base_model/utils.py
> +    print(f"[{name}] done in {time.time() - t0:.0f} s")
Может, лучше logging вместо принтов сделать?
Ещё слышал, что настоящие мушкетёры предпочитают тайминг функций делать через `time.perf_counter()` и декоратор, а не контекстный менеджер.

2022-04-07 14:04 UTC, Yorko commented on cryptonews_sentiment_base_model/train.py
> +    cross_val_params = params["cross_validation"]
fixed in 5eef6c9

2022-04-07 14:05 UTC, Yorko commented on cryptonews_sentiment_base_model/model.py
> +    params: Dict[str, Any] = yaml.load(f, Loader=yaml.FullLoader)
fixed in 5eef6c9

2022-04-07 14:08 UTC, Yorko commented on cryptonews_sentiment_base_model/utils.py
> +    print(f"[{name}] done in {time.time() - t0:.0f} s")
> Ещё слышал, что настоящие мушкетёры предпочитают тайминг функций делать через time.perf_counter() и декоратор, а не контекстный менеджер.

Это уже вкусовщина. Мне, например, больше нравится определить в утилах контекстный менеджер и дальше его только вызывать. По крайней мере, [это](https://www.geeksforgeeks.org/time-perf_counter-function-in-python/) менее красиво выглядит. 

Да, принты на logging стоит заменить

2022-04-07 14:20 UTC, labdmitriy commented
Мы планируем пользоваться typing annotations?
Просто без mypy особенной пользы, по моему небольшому опыту использования, нет. Что думаете?

Кстати, для python 3.9+ можно вместо некоторых типов из typing (например, List/Dict), использовать встроенные типы (list/dict) без доп. импортов.

Сейчас в pyproject.toml указаны python-версии 3.8 и 3.9, может сразу перейти нам на последнюю версию (3.10.4)? Или у нас какие-то ограничения есть.

2022-04-07 14:28 UTC, aleksandrinvictor approved these changes

2022-04-07 14:37 UTC, aleksandrinvictor commented
> Мы планируем пользоваться typing annotations? Просто без mypy особенной пользы, по моему небольшому опыту использования, нет. Что думаете?
> 
> Кстати, для python 3.9+ можно вместо некоторых типов из typing (например, List/Dict), использовать встроенные типы (list/dict) без доп. импортов.
> 
> Сейчас в pyproject.toml указаны python-версии 3.8 и 3.9, может сразу перейти нам на последнюю версию (3.10.4)? Или у нас какие-то ограничения есть.

Кажется typing hints нужно использовать в любом случае, чтобы лучше понимать чужой код. Mypy думаю тоже стоит добавить.

2022-04-07 14:41 UTC, labdmitriy commented
> > Мы планируем пользоваться typing annotations? Просто без mypy особенной пользы, по моему небольшому опыту использования, нет. Что думаете?
> > Кстати, для python 3.9+ можно вместо некоторых типов из typing (например, List/Dict), использовать встроенные типы (list/dict) без доп. импортов.
> > Сейчас в pyproject.toml указаны python-версии 3.8 и 3.9, может сразу перейти нам на последнюю версию (3.10.4)? Или у нас какие-то ограничения есть.
> 
> Кажется typing hints нужно использовать в любом случае, чтобы лучше понимать чужой код. Mypy думаю тоже стоит добавить.

Аннотация и в документации хорошо будет смотреться, можно будет по идее sphinx + readthedocs использовать для ее создания. 
Я пробовал генерацию на прошлом проекте учебном (https://hat-client.readthedocs.io/en/latest/readme.html#description), если у кого-то больше опыта в этом - было бы отлично послушать про это.

2022-04-08 09:57 UTC, Yorko commented on cryptonews_sentiment_base_model/utils.py
> +    print(f"[{name}] done in {time.time() - t0:.0f} s")
added in 1b7d674

2022-04-10 18:06 UTC, glotars approved these changes

2022-04-11 10:17 UTC, ZakharovNerd approved these changes

2022-04-11 21:33 UTC, LinkaG approved these changes

2022-04-11 23:18 UTC, merged